framework:
    messenger:
        transports:
            events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                    queues:
                        master_events: ~
                        slave_events: ~
            master:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        master_events: ~
            slave:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        slave_events: ~
        routing:
            'App\Messages\RedirectThisMessage': events
