framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: requests
                    queues:
                        redirect: ~
                        scan_chat: ~
                        scan_user: ~
        routing:
            'App\Messages\RedirectThisMessage': async
