framework:
    messenger:
        transports:
            proxy:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: proxy
                    queues:
                        master: ~
                        slave: ~
            master:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        master: ~
            slave:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        slave: ~
        routing:
            'App\Messages\RedirectThisMessage': proxy
